### ISSUE TITLE
Fatal error upon install

### ISSUE THREAD

**Issue by mfefer** [asselapathirana/epanettools#23]
Hello,

I'm having issues trying to install the package. I've tried a few different methods of installation (pip, direct download from PyPi, and cloning Github repository) but still receive the same error upon using the ```pip``` command or ```python setup.py install``` command.

```
src/epanettools/epanet/epanet.c:135:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

Running the command using ```sudo``` also did not help. Any ideas on what this ```malloc.h``` file is?

Thanks.

**Comment by claytonpbarrows** [comment]
@mfefer did you ever resolve your issue? I'm having the same problem.

**Comment by claytonpbarrows** [comment]
I did get a successful install by creating a dummy `malloc.h` file 
```
touch src/epanettools/epanet/malloc.h
```
