### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by Noyoy** [asselapathirana/epanettools#24]
Hey,  
When i'm "pip install epanettools",
I'm getting the following message: "error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools"

After installing VS C++ build tools, the error message is still on... 
Any ideas?  
Thanks!
---------------------
Run on Win 10

**Comment by asselapathirana** [comment]
Hi, I don't have access to a Windows 10 computer. I could only test these in windows 7 and linux OS. However, can you make sure the following: 

1. There are reported issues with python 3.5 - by any chance are you running python 3.5 - if so, try either with 3.6 or 3.4. 
2. VS C++ build tools have a number of different versions. Each python version uses a different VC C++ version. So, make sure that you install VS C++ 14.00 build tools. 

Hope this helps.
