### ISSUE TITLE
Having problem installing

### ISSUE THREAD

**Issue by zhanxy13** [asselapathirana/epanettools#25]
Hi Assela,

I failed to pip install the epanettools package. It said Failed building wheel for epanettools.....Command... failed with error code 1. I think the problem is I used Python3.5 and there's no wheel file for it. Could you please upload the .whl file for  3.5 version?

Thanks in advance.

**Comment by asselapathirana** [comment]
Hi zhanxy13, 
I also failed to build the wheel for python 3.5. I'll try this again when I have some time. But, for the moment, my advice is to use either version 3.4 or 3.6 (both works well). 
Assela

**Comment by zhanxy13** [comment]
Thanks for your reply. I will try on version 3.6 then :)
